import type {
  Attendance,
  AuditLog,
  Cell,
  CellGroup,
  Meeting,
  Notification,
  Participant,
  ParticipantNote,
  Profile,
  WorkspaceData,
} from "./types";

export const demoProfiles: Profile[] = [
  {
    id: "profile-admin",
    fullName: "Catiana Souza",
    email: "catiana.souza@wifi.com",
    phone: "(11) 90000-0001",
    role: "admin",
    active: true,
    createdAt: "2026-06-01T12:00:00.000Z",
    updatedAt: "2026-08-01T12:00:00.000Z",
  },
  {
    id: "profile-leader-maria",
    fullName: "Maria Clara Brazil",
    email: "maria.clara@wifi.com",
    phone: "(11) 90000-0011",
    role: "leader",
    groupId: "group-maria",
    participantId: "p-maria-clara-brazil",
    active: true,
    createdAt: "2026-06-01T12:00:00.000Z",
    updatedAt: "2026-08-01T12:00:00.000Z",
  },
  {
    id: "profile-leader-sarah",
    fullName: "Sarah",
    email: "sarah@wifi.com",
    phone: "(11) 90000-0012",
    role: "leader",
    groupId: "group-sarah",
    participantId: "p-sarah-lider",
    active: true,
    createdAt: "2026-06-01T12:00:00.000Z",
    updatedAt: "2026-08-01T12:00:00.000Z",
  },
  {
    id: "profile-leader-samuel",
    fullName: "Samuel Amaro",
    email: "samuel.amaro@wifi.com",
    phone: "(11) 90000-0013",
    role: "leader",
    groupId: "group-samuel",
    participantId: "p-samuel-amaro",
    active: true,
    createdAt: "2026-06-01T12:00:00.000Z",
    updatedAt: "2026-08-01T12:00:00.000Z",
  },
];

export const demoCells: Cell[] = [
  {
    id: "cell-wifi",
    name: "WiFi",
    description: "Conectados com Deus e uns com os outros.",
    address: "Rua das Flores, 129",
    neighborhood: "Jardim Esperanca",
    city: "Sao Paulo",
    weekday: "Sexta-feira",
    startTime: "19:30",
    hostName: "Familia Alves",
    contactPhone: "(11) 98888-1221",
    active: true,
    createdAt: "2026-06-01T12:00:00.000Z",
    updatedAt: "2026-08-01T12:00:00.000Z",
  },
];

export const demoGroups: CellGroup[] = [
  {
    id: "group-maria",
    cellId: "cell-wifi",
    name: "Grupo Maria Clara",
    description: "Adolescentes acompanhadas por Maria Clara Brazil.",
    color: "violet",
    leaderProfileId: "profile-leader-maria",
    leaderParticipantId: "p-maria-clara-brazil",
    active: true,
    createdAt: "2026-06-01T12:00:00.000Z",
    updatedAt: "2026-08-01T12:00:00.000Z",
  },
  {
    id: "group-sarah",
    cellId: "cell-wifi",
    name: "Grupo Sarah",
    description: "Grupo liderado por Sarah.",
    color: "rose",
    leaderProfileId: "profile-leader-sarah",
    leaderParticipantId: "p-sarah-lider",
    active: true,
    createdAt: "2026-06-01T12:00:00.000Z",
    updatedAt: "2026-08-01T12:00:00.000Z",
  },
  {
    id: "group-samuel",
    cellId: "cell-wifi",
    name: "Grupo Samuel",
    description: "Grupo liderado por Samuel Amaro.",
    color: "cyan",
    leaderProfileId: "profile-leader-samuel",
    leaderParticipantId: "p-samuel-amaro",
    active: true,
    createdAt: "2026-06-01T12:00:00.000Z",
    updatedAt: "2026-08-01T12:00:00.000Z",
  },
];

const baseParticipants: Array<
  Pick<
    Participant,
    | "id"
    | "groupId"
    | "fullName"
    | "preferredName"
    | "age"
    | "birthDate"
    | "phone"
    | "whatsapp"
    | "email"
    | "neighborhood"
    | "joinedAt"
    | "participantType"
    | "status"
    | "invitedBy"
    | "firstVisitAt"
    | "notes"
  >
> = [
  {
    id: "p-maria-clara-brazil",
    groupId: "group-maria",
    fullName: "Maria Clara Brazil",
    preferredName: "Maria Clara",
    age: 17,
    joinedAt: "2026-08-01",
    participantType: "leader",
    status: "active",
  },
  {
    id: "p-sthefany-barbosa",
    groupId: "group-maria",
    fullName: "Sthefany Barbosa",
    preferredName: "Sthefany",
    age: 14,
    joinedAt: "2026-08-01",
    participantType: "teenager",
    status: "active",
  },
  {
    id: "p-amanda-feijoli",
    groupId: "group-maria",
    fullName: "Amanda Feijoli",
    preferredName: "Amanda",
    age: 13,
    joinedAt: "2026-08-01",
    participantType: "teenager",
    status: "active",
  },
  {
    id: "p-giovanna-campos",
    groupId: "group-maria",
    fullName: "Giovanna Campos",
    preferredName: "Giovanna",
    age: 13,
    joinedAt: "2026-08-01",
    participantType: "teenager",
    status: "active",
  },
  {
    id: "p-marcelle-fagundes",
    groupId: "group-maria",
    fullName: "Marcelle Fagundes",
    preferredName: "Marcelle",
    age: 13,
    joinedAt: "2026-08-01",
    participantType: "teenager",
    status: "active",
  },
  {
    id: "p-luiza-brazil",
    groupId: "group-maria",
    fullName: "Luiza Brazil",
    preferredName: "Luiza",
    age: 12,
    joinedAt: "2026-08-01",
    participantType: "teenager",
    status: "active",
  },
  {
    id: "p-emanuela-mello",
    groupId: "group-maria",
    fullName: "Emanuela Mello",
    preferredName: "Emanuela",
    age: 11,
    joinedAt: "2026-08-01",
    participantType: "child",
    status: "active",
  },
  {
    id: "p-giovanna-vieira",
    groupId: "group-maria",
    fullName: "Giovanna Vieira",
    preferredName: "Giovanna",
    age: 12,
    joinedAt: "2026-08-01",
    participantType: "teenager",
    status: "active",
  },
  {
    id: "p-luiza-helena-jesus",
    groupId: "group-maria",
    fullName: "Luiza Helena de Jesus",
    preferredName: "Luiza Helena",
    age: 13,
    joinedAt: "2026-08-01",
    participantType: "teenager",
    status: "active",
  },
  {
    id: "p-mirela-moreira",
    groupId: "group-maria",
    fullName: "Mirela Moreira",
    preferredName: "Mirela",
    age: 12,
    joinedAt: "2026-08-01",
    participantType: "teenager",
    status: "active",
  },
  {
    id: "p-manuella-gomes-chagas",
    groupId: "group-maria",
    fullName: "Manuella Gomes Chagas",
    preferredName: "Manuella",
    age: 11,
    joinedAt: "2026-08-01",
    participantType: "child",
    status: "active",
  },
  {
    id: "p-giovanna-oliveira",
    groupId: "group-maria",
    fullName: "Giovanna de Oliveira",
    preferredName: "Giovanna",
    age: 11,
    joinedAt: "2026-08-01",
    participantType: "child",
    status: "active",
  },
  {
    id: "p-thaissa-lorena-ferreira",
    groupId: "group-maria",
    fullName: "Thaissa Lorena Ferreira",
    preferredName: "Thaissa",
    age: 12,
    joinedAt: "2026-08-01",
    participantType: "teenager",
    status: "active",
  },
  {
    id: "p-vitoria-silva",
    groupId: "group-maria",
    fullName: "Vitoria Silva",
    preferredName: "Vitoria",
    age: 13,
    joinedAt: "2026-08-01",
    participantType: "teenager",
    status: "active",
  },
  {
    id: "p-marcella-barbosa",
    groupId: "group-maria",
    fullName: "Marcella Barbosa",
    preferredName: "Marcella",
    age: 13,
    joinedAt: "2026-08-01",
    participantType: "teenager",
    status: "active",
  },
  {
    id: "p-julia-barbosa",
    groupId: "group-maria",
    fullName: "Julia Barbosa",
    preferredName: "Julia",
    age: 12,
    joinedAt: "2026-08-01",
    participantType: "teenager",
    status: "active",
  },
  {
    id: "p-isabel-borges",
    groupId: "group-maria",
    fullName: "Isabel Borges",
    preferredName: "Isabel",
    age: 12,
    joinedAt: "2026-08-01",
    participantType: "teenager",
    status: "active",
  },
  {
    id: "p-sarah-lider",
    groupId: "group-sarah",
    fullName: "Sarah",
    preferredName: "Sarah",
    age: 17,
    joinedAt: "2026-08-01",
    participantType: "leader",
    status: "active",
  },
  {
    id: "p-hannah",
    groupId: "group-sarah",
    fullName: "Hannah",
    preferredName: "Hannah",
    age: 16,
    joinedAt: "2026-08-01",
    participantType: "teenager",
    status: "active",
  },
  {
    id: "p-geovana-amaro",
    groupId: "group-sarah",
    fullName: "Geovana Amaro",
    preferredName: "Geovana",
    age: 15,
    joinedAt: "2026-08-01",
    participantType: "teenager",
    status: "active",
  },
  {
    id: "p-rafaela",
    groupId: "group-sarah",
    fullName: "Rafaela",
    preferredName: "Rafaela",
    age: 16,
    joinedAt: "2026-08-01",
    participantType: "teenager",
    status: "active",
  },
  {
    id: "p-samuel-amaro",
    groupId: "group-samuel",
    fullName: "Samuel Amaro",
    preferredName: "Samuel",
    age: 18,
    joinedAt: "2026-08-01",
    participantType: "leader",
    status: "active",
  },
  {
    id: "p-nathanel",
    groupId: "group-samuel",
    fullName: "Nathanel",
    preferredName: "Nathanel",
    age: 16,
    joinedAt: "2026-08-01",
    participantType: "teenager",
    status: "active",
  },
  {
    id: "p-samuel-santoro",
    groupId: "group-samuel",
    fullName: "Samuel Santoro",
    preferredName: "Samuel",
    age: 14,
    joinedAt: "2026-08-01",
    participantType: "teenager",
    status: "active",
  },
  {
    id: "p-kayque-souza",
    groupId: "group-samuel",
    fullName: "Kayque Souza",
    preferredName: "Kayque",
    age: 16,
    joinedAt: "2026-08-01",
    participantType: "teenager",
    status: "active",
  },
  {
    id: "p-kayque-ribeiro",
    groupId: "group-samuel",
    fullName: "Kayque Ribeiro",
    preferredName: "Kayque",
    age: 16,
    joinedAt: "2026-08-01",
    participantType: "teenager",
    status: "active",
  },
  {
    id: "p-gustavo-pinhal",
    groupId: "group-samuel",
    fullName: "Gustavo Pinhal",
    preferredName: "Gustavo",
    age: 16,
    joinedAt: "2026-08-01",
    participantType: "teenager",
    status: "active",
  },
  {
    id: "p-pedro-valentin",
    groupId: "group-samuel",
    fullName: "Pedro Valentin",
    preferredName: "Pedro",
    age: 13,
    joinedAt: "2026-08-01",
    participantType: "teenager",
    status: "active",
  },
  {
    id: "p-heitor-nascimento",
    groupId: "group-samuel",
    fullName: "Heitor Nascimento",
    preferredName: "Heitor",
    age: 13,
    joinedAt: "2026-08-01",
    participantType: "teenager",
    status: "active",
  },
  {
    id: "p-brayan",
    groupId: "group-samuel",
    fullName: "Brayan",
    preferredName: "Brayan",
    age: 15,
    joinedAt: "2026-08-01",
    participantType: "teenager",
    status: "active",
  },
];

export const demoParticipants: Participant[] = baseParticipants.map((person) => ({
  ...person,
  cellId: "cell-wifi",
  active: person.status !== "inactive",
  createdBy: "profile-admin",
  createdAt: `${person.joinedAt}T12:00:00.000Z`,
  updatedAt: "2026-08-01T12:00:00.000Z",
}));

export const demoMeetings: Meeting[] = [];

export const demoAttendance: Attendance[] = [];

export const demoNotifications: Notification[] = [];

export const demoParticipantNotes: ParticipantNote[] = [];

export const demoAuditLogs: AuditLog[] = [];

export const demoWorkspaceData: WorkspaceData = {
  currentUser: demoProfiles[0],
  cell: demoCells[0],
  profiles: demoProfiles,
  cells: demoCells,
  groups: demoGroups,
  participants: demoParticipants,
  meetings: demoMeetings,
  attendance: demoAttendance,
  notifications: demoNotifications,
  participantNotes: demoParticipantNotes,
  auditLogs: demoAuditLogs,
};
